spring.application.name=FinanceDataMigration
server.port=${PORT:8000}
spring.profile=${PROFILE:local}

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

finance.expense.bill.create-url =/rest/bill/expense/create
finance.contractor.bill.create-url =/rest/bill/expense/create
finance.supplier.bill.create-url =/rest/bill/supplier/create

# Finance Base URL
finance.base-url=https://finance.ulbharyana.gov.in/

#Local finance hit
finance.local.baseurl = http://localhost:9090/services/EGF

# OAuth Token API
finance.auth.token-url=${finance.base-url}user/oauth/token

# Migration API Endpoints
finance.voucher.create-url = ${finance.local.baseurl}/rest/voucher/_create
finance.bank.create-url = ${finance.local.baseurl}/bank/rest/create
finance.fund.create-url = ${finance.local.baseurl}/fund/rest/create
finance.scheme.create-url = ${finance.local.baseurl}/scheme/rest/create
finance.bankbranch.create-url = ${finance.local.baseurl}/bankbranch/rest/create
finance.bankaccount.create-url = ${finance.local.baseurl}/bankaccount/rest/create
finance.work.create-url= ${finance.local.baseurl}/rest/work/create
finance.workorder.create-url= ${finance.local.baseurl}/rest/workorder/create
finance.purchaseorder.create-url=${finance.local.baseurl}/rest/purchaseorder/create
finance.contractor.create-url = ${finance.local.baseurl}/contractor/rest/create
finance.supplier.create-url = ${finance.local.baseurl}/supplier/rest/create
finance.contractor-bill.create-url= ${finance.local.baseurl}/rest/bill/contractor/create

# Search Endpoint
fund.search=/funds/_search
scheme.search=/scheme/_search
function.search=/functions/_search
glcode.search=/rest/common/v1/getChartAccountCodeByGlCode
workorder.search=/rest/workorder/


# OAuth Authorization Header
finance.auth.authorization-key=Basic ZWdvdi11c2VyLWNsaWVudDo=

# System Integration User
finance.auth.username=SIFINANCE
finance.auth.password=eGov@4321

# OAuth Parameters
finance.auth.grant-type=password
finance.auth.scope=read

# Tenant
# finance.tenant=hr.gurugram
finance.tenants=hr.gurugram,hr.kalka,hr.panchkula,hr.sohna,hr.rewari,hr.thanesar,hr.farrukhnagar,hr.panipat,hr.samalkha,hr.sampla,hr.kundli,hr.ratia,hr.manesar,hr.pataudi,hr.palwal,hr.hathin,hr.yamunanagar,hr.sadhaura,hr.radaur,hr.sirsa,hr.rania,hr.mandidabwali,hr.kalanwali,hr.ellenabad,hr.sonipat,hr.kharkhoda,hr.gohana,hr.ganaur,hr.rohtak,hr.meham,hr.kalanaur,hr.dharuhera,hr.bawal,hr.hodal,hr.faridabad,hr.charkhidadri,hr.narnaund,hr.hansi,hr.tauru,hr.punhana,hr.nuh,hr.firozpurzhirka,hr.narnaul,hr.nangalchaudhary,hr.mahendergarh,hr.kanina,hr.atelimandi,hr.shahabad,hr.pehowa,hr.ladwa,hr.ismailabad,hr.tarori,hr.nissing,hr.nilokheri,hr.karnal,hr.indri,hr.gharaunda,hr.assandh,hr.siwan,hr.rajaund,hr.pundri,hr.kalayat,hr.kaithal,hr.cheeka,hr.uchana,hr.safidon,hr.narwana,hr.julana,hr.jind,hr.jhajjar,hr.beri,hr.bahadurgarh,hr.uklana,hr.hisar,hr.barwala,hr.tohana,hr.jakhal,hr.fatehabad,hr.bhuna,hr.siwani,hr.loharu,hr.bhiwani,hr.bawanikhera,hr.naraingarh,hr.barara,hr.ambalasadar,hr.ambala

# PostgreSQL Database
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/upyog_migration?sslmode=disable}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
