# ==============================
# Stage 1: Build
# ==============================
FROM maven:3.9-eclipse-temurin-17 AS builder

WORKDIR /app

# Copy Maven configuration first
# Helps Docker cache dependencies
COPY pom.xml .

RUN mvn dependency:go-offline -B

# Copy source code
COPY src ./src

# Build application
RUN mvn clean package -DskipTests


# ==============================
# Stage 2: Runtime
# ==============================
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

# Create non-root user
RUN addgroup -S appgroup && \
    adduser -S appuser -G appgroup

# Copy JAR
COPY --from=builder /app/target/*.war app.war

# Give application user ownership
RUN chown -R appuser:appgroup /app

# Run as non-root
USER appuser

#POR
EXPOSE 8000

# Optional JVM options
ENV JAVA_OPTS=""

# Start Spring Boot
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.war"]